### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by dlemstra**
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

This PR adds eslint to the project and fixes isue #32. For the configuration a default is used that uses the default rules and has some tweaks based on the code in the project. I don't mind changing this if @dkundel would like to use a different configuration. This PR also adds eslint to the travis build.

### CODE REVIEW

**Comment by dkundel** [comment]
I'll let @philnash call the shots here but he's currently at an event. But I wonder if we should use https://www.npmjs.com/package/eslint-config-twilio. It's not open source yet but for consistency it might be nice.

**Comment by dkundel** [comment]
@ahcai any concerns about this?

**Comment by philnash** [comment]
So, the tests are now failing because of the linting. Is that expected? 

There seems like a lot of fails, so would it be best to remove linting from CI for now, get this work merged in and then start fixing the errors? Or should we get to work fixing them in this PR?

**Comment by dlemstra** [comment]
I am planning to fix all those issues in this PR. But I am waiting with this until there is an answer to my open issues in the twilio-style
 project.

**Comment by ktalebian** [comment]
@dkundel I think we can use the eslinter. @ahcai and I will be adding Typescript and prettier support in the near future, but the JS work is mostly done. There may be very minor tweaks to some of the rules as we start using it in production, but shouldn't be anything that `--fix` would not be able to auto-fix.

**Comment by dkundel** [comment]
Alright @ktalebian if you have no concerns, @dlemstra feel free to fix the tests that are currently failing and then I'll let @philnash pull the trigger here :) but from my side it looks good

**Comment by dlemstra** [comment]
Fixed some more of the failing tests but I am not sure what to do with the remaining ones that are still failing. Wondering if the config needs to be tweaked for this.

**Comment by philnash** [comment]
How do we feel about excluding test files from linting?

The remaining `no-console` issues are a pain for a command line application like this. Can we add a specific opt out for that in this project?

The `importCredentials` shadow can be fixed by renaming the result of the question to something different. This requires an update in the test too, as it is stubbed with that name.

```javascript
// import-credentials.js
const questions = [
  {
    type: 'confirm',
    name: 'importedCredentials',
    message:
      'Your account credentials have been found in your environment variables. Import them?',
    default: true,
  },
];

// then at the bottom:
  const { importedCredentials } = await inquirer.prompt(questions);
  return importedCredentials ? credentials : {};
}
```

Then in the test, everywhere the result is mocked, we can change that to:

```
  inquirer.prompt = jest.fn(() => Promise.resolve({ importedCredentials: true }));
```

The `no-param-reassign` rule is annoying, but we can get around that with one more assignment at the top of `createTwilioFunction`.

What do you think?

**Comment by dlemstra** [comment]
I don't think that the test folder should be excluded from the list. I just pushed some patches to fix the remaining errors and I updated `slint-config-twilio` to the latest version. The build now passes on Linux but fails on Windows due to new line issues. Once https://github.com/twilio-labs/twilio-style/issues/24 has been addressed we can get this merged.

**Comment by dlemstra** [comment]
Looks like everything works now @philnash. Lets merge this?

**Comment by philnash** [comment]
Turned out we'd added more rules, so I had 58 more things to fix 😅

This is merged now. Thanks for your work on this @dlemstra!

**Pull request merged**
