### PR TITLE
[feature] added update-notifier for the package

### PR DESCRIPTION
**Pull request by anikethsaha**
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

Added the `update-notifier` package for informing users whenever update of this package comes.

No breaking changes

### CODE REVIEW

**Comment by philnash** [comment]
Hey @anikethsaha, thanks for this, I didn't know about the `update-notifier` package.

I'm not sure this is the best thing for this project though. While it is used as a standalone project it also forms part of the [serverless-toolkit](https://github.com/twilio-labs/serverless-toolkit) and the [serverless plugin for the Twilio CLI](https://github.com/twilio-labs/plugin-serverless). It would be odd for a user of the plugin and CLI (which can be installed via homebrew as well as by npm) to be told to update an internal package. I couldn't find anything in `update-notifier`'s documentation that allow you to avoid it notifying if it is run as part of another module.

On the other hand, `create-twilio-function` is not really intended to be installed globally, rather it should be run with `npm init twilio-function` or `npx create-twilio-function` which should load the latest available version anyway.

What do you think @dkundel?

**Comment by anikethsaha** [comment]
I didn't get your first point? You meant these three packages are related and their version need to be synced? 
And about the second point, yeah that makes sense. 
Please let me know if this PR needs to be closed or not. I guess it's not that necessary to have `uodate-notifier` integrated!

**Comment by philnash** [comment]
The first point is that this is a standalone package, however it is also used as a library for a completely different CLI component, as a plugin to the Twilio CLI. It's not that the versions need to be synced, just that the code from this function may run as part of a different tool that is installed via homebrew and that this message wouldn't be appropriate there.

I am leaning towards closing the PR, just waiting to see what my colleague thinks too.

**Comment by anikethsaha** [comment]
ok sure

**Pull request closed without merging**
